In [5]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import jieba

In [8]:
def dictvec():
    dict = DictVectorizer(sparse=False)
    data = dict.fit_transform([{"city":"北京","temperature":45},{"city":"上海","temperature":32},
                               {"city":"南京","temperature":20}])
    print(type(data))
    print(data)
    print(dict.get_feature_names_out())
    print(dict.inverse_transform(data))
dictvec()

<class 'numpy.ndarray'>
[[ 0.  1.  0. 45.]
 [ 1.  0.  0. 32.]
 [ 0.  0.  1. 20.]]
['city=上海' 'city=北京' 'city=南京' 'temperature']
[{'city=北京': 1.0, 'temperature': 45.0}, {'city=上海': 1.0, 'temperature': 32.0}, {'city=南京': 1.0, 'temperature': 20.0}]
